### PR TITLE
make tunable number class for tuning

### PR DESCRIPTION
**Pull request by Shazamboo**
## Justification
 tunable number because its nice to have for testing (could use it on turret hint hint)

## Implementaion
 took tunable number class and put it in the code. Also moved debug entry to utilities folder cause having a folder called network tables is misleading.

### CODE REVIEW

**Comment by zbrotherton** [comment]
ROLL IT THROUGH 🗣️🗣️🗣️

**Review by riversry — DISMISSED** [review]
good

**Review by riversry — APPROVED** [review]
good

**Review by zbrotherton — APPROVED** [review]
image

**Review by caseyjbrotherton — APPROVED** [review]

**Pull request merged**
